{
 "title": "Práctica grafana dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": {
     "query": "kube_deployment_status_condition{ condition =~ \"Available\"} "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployments disponibles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_condition{ deployment=\"$deployment\", condition =~ \"Available\", status =~ \"true\"}",
     "legendFormat": "Deployment: {{ deployment }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 18, "w": 1, "x": 12, "y": 0 },
   "options": {
    "content": "<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n<center>|</center>\n"
   }
  },
  {
   "title": "Pods del deployement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_info {pod =~ \"$deployment-.*\"}",
     "legendFormat": "Pods: {{ pod }}"
    }
   ]
  },
  {
   "title": "Uso total de CPU de todos los pods ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod =~ \"$deployment-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Uso total de memoria de todos los pods ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod =~ \"$deployment-.*\"})"
    }
   ]
  },
  {
   "title": "Número de reiniciosde los pods por deployment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_restart_policy {pod =~ \"$deployment-.*\"}",
     "legendFormat": "Pod: {{ pod}}"
    }
   ]
  }
 ]
}